version: '3'

services:
    web-nginx:
        image: nginx:stable-alpine
        container_name: web-nginx
        restart: always
        deploy:
          replicas: 3
        ports:
          - "8080:80"
        
    web-php:
        image: php:fpm-alpine
        container_name: web-php
        deploy:
          replicas: 2
    web-db:
        image: postgres
        restart: always
        ports:
          - "3306:3306"
        environment:
           POSTGRES_PASSWORD: password
networks:
  proxy:
    external: true
