version: '3'

services:
    web-nginx:
        image: nginx:stable-alpine
        container_name: web-nginx
        restart: always
        deploy:
          replicas: 2
        volumes:
            - "./www:/usr/share/nginx/html:ro"
            - "./log:/var/log/nginx"
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "8080:80"
        
    web-php:
        image: php:fpm-alpine
        container_name: web-php
        deploy:
          replicas: 2
        volumes:
            - "./www:/script:ro"
    web-db:
        image: postgres
        restart: always
        environment:
           POSTGRES_PASSWORD: password
networks:
  proxy:
    external: true
